login_check:
    pattern: /login_check

logout:
    pattern: /logout

ens_jobeet:
    resource: "@EnsJobeetBundle/Controller"
    type: annotation

sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
